[2024-12-16T14:37:30.318+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-16T14:37:30.329+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.second_task manual__2024-12-16T14:37:25+00:00 [queued]>
[2024-12-16T14:37:30.334+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.second_task manual__2024-12-16T14:37:25+00:00 [queued]>
[2024-12-16T14:37:30.335+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-16T14:37:30.344+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): second_task> on 2024-12-16 14:37:25+00:00
[2024-12-16T14:37:30.349+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-16T14:37:30.350+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'MI_PRIMER_DAG', 'second_task', 'manual__2024-12-16T14:37:25+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/MI_PRIMER_DAG.py', '--cfg-path', '/tmp/tmpy4hw79ak']
[2024-12-16T14:37:30.350+0000] {standard_task_runner.py:72} INFO - Started process 71 to run task
[2024-12-16T14:37:30.350+0000] {standard_task_runner.py:105} INFO - Job 136: Subtask second_task
[2024-12-16T14:37:30.385+0000] {task_command.py:467} INFO - Running <TaskInstance: MI_PRIMER_DAG.second_task manual__2024-12-16T14:37:25+00:00 [running]> on host 590f5de10d76
[2024-12-16T14:37:30.443+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='MI_PRIMER_DAG' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T14:37:25+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T14:37:25+00:00'
[2024-12-16T14:37:30.444+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-16T14:37:30.444+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-16T14:37:30.444+0000] {logging_mixin.py:190} INFO - Current task name:second_task state:running start_date:2024-12-16 14:37:30.330231+00:00
[2024-12-16T14:37:30.444+0000] {logging_mixin.py:190} INFO - Dag name:MI_PRIMER_DAG and current dag run status:running
[2024-12-16T14:37:30.445+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-16T14:37:30.445+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 55, in second_tasks
    if manual:
       ^^^^^^
NameError: name 'manual' is not defined
[2024-12-16T14:37:30.453+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-16T14:37:30.454+0000] {logging_mixin.py:190} INFO - Task start:2024-12-16 14:37:30.330231+00:00 end:2024-12-16 14:37:30.453278+00:00 duration:0.123047
[2024-12-16T14:37:30.454+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): second_task> dag:<DAG: MI_PRIMER_DAG> dagrun:<DagRun MI_PRIMER_DAG @ 2024-12-16 14:37:25+00:00: manual__2024-12-16T14:37:25+00:00, state:running, queued_at: 2024-12-16 14:37:28.184546+00:00. externally triggered: True>
[2024-12-16T14:37:30.454+0000] {logging_mixin.py:190} INFO - Failure caused by name 'manual' is not defined
[2024-12-16T14:37:30.455+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=MI_PRIMER_DAG, task_id=second_task, run_id=manual__2024-12-16T14:37:25+00:00, execution_date=20241216T143725, start_date=20241216T143730, end_date=20241216T143730
[2024-12-16T14:37:30.462+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-16T14:37:30.463+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 136 for task second_task (name 'manual' is not defined; 71)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 55, in second_tasks
    if manual:
       ^^^^^^
NameError: name 'manual' is not defined
[2024-12-16T14:37:30.484+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-16T14:37:30.499+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-16T14:37:30.500+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
