[2024-09-30T14:20:03.100+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-30T14:20:03.111+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:19:58+00:00 [queued]>
[2024-09-30T14:20:03.116+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:19:58+00:00 [queued]>
[2024-09-30T14:20:03.117+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 5
[2024-09-30T14:20:03.127+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): first_task> on 2024-09-30 14:19:58+00:00
[2024-09-30T14:20:03.131+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T14:20:03.133+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'MI_PRIMER_DAG', 'first_task', 'manual__2024-09-30T14:19:58+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/MI_PRIMER_DAG.py', '--cfg-path', '/tmp/tmpwqry1ujz']
[2024-09-30T14:20:03.133+0000] {standard_task_runner.py:72} INFO - Started process 69 to run task
[2024-09-30T14:20:03.133+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask first_task
[2024-09-30T14:20:03.166+0000] {task_command.py:467} INFO - Running <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:19:58+00:00 [running]> on host b81766f0ac39
[2024-09-30T14:20:03.223+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='MI_PRIMER_DAG' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T14:19:58+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-30T14:19:58+00:00'
[2024-09-30T14:20:03.225+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-30T14:20:03.225+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-30T14:20:03.225+0000] {logging_mixin.py:190} INFO - Current task name:first_task state:running start_date:2024-09-30 14:20:03.112223+00:00
[2024-09-30T14:20:03.226+0000] {logging_mixin.py:190} INFO - Dag name:MI_PRIMER_DAG and current dag run status:running
[2024-09-30T14:20:03.226+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-30T14:20:03.226+0000] {logging_mixin.py:190} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7f5b26bbcf20>, 'dag': <DAG: MI_PRIMER_DAG>, 'dag_run': <DagRun MI_PRIMER_DAG @ 2024-09-30 14:19:58+00:00: manual__2024-09-30T14:19:58+00:00, state:running, queued_at: 2024-09-30 14:20:00.640706+00:00. externally triggered: True>, 'data_interval_end': DateTime(2024, 9, 30, 9, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2024, 9, 29, 9, 0, 0, tzinfo=Timezone('UTC')), 'outlet_events': <***.utils.context.OutletEventAccessors object at 0x7f5b26c04b30>, 'ds': '2024-09-30', 'ds_nodash': '20240930', 'execution_date': <Proxy at 0x7f5afca58600 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'execution_date', DateTime(2024, 9, 30, 14, 19, 58, tzinfo=Timezone('UTC')))>, 'expanded_ti_count': None, 'inlets': [], 'inlet_events': InletEventsAccessors(_inlets=[], _datasets={}, _dataset_aliases={}, _session=<sqlalchemy.orm.session.Session object at 0x7f5b26c006b0>), 'logical_date': DateTime(2024, 9, 30, 14, 19, 58, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.12/site-packages/***/macros/__init__.py'>, 'map_index_template': None, 'next_ds': <Proxy at 0x7f5afca31940 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'next_ds', '2024-09-30')>, 'next_ds_nodash': <Proxy at 0x7f5afcad73c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'next_ds_nodash', '20240930')>, 'next_execution_date': <Proxy at 0x7f5afcc8ae80 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'next_execution_date', DateTime(2024, 9, 30, 14, 19, 58, tzinfo=Timezone('UTC')))>, 'outlets': [], 'params': {'Manual': True}, 'prev_data_interval_start_success': DateTime(2024, 9, 29, 9, 0, 0, tzinfo=Timezone('UTC')), 'prev_data_interval_end_success': DateTime(2024, 9, 30, 9, 0, 0, tzinfo=Timezone('UTC')), 'prev_ds': <Proxy at 0x7f5afcb89c40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'prev_ds', '2024-09-30')>, 'prev_ds_nodash': <Proxy at 0x7f5afca97d00 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'prev_ds_nodash', '20240930')>, 'prev_execution_date': <Proxy at 0x7f5afca97f40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'prev_execution_date', DateTime(2024, 9, 30, 14, 19, 58, tzinfo=Timezone('UTC')))>, 'prev_execution_date_success': <Proxy at 0x7f5afca0b480 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'prev_execution_date_success', DateTime(2024, 9, 29, 9, 0, 0, tzinfo=Timezone('UTC')))>, 'prev_start_date_success': DateTime(2024, 9, 30, 14, 12, 35, 739653, tzinfo=Timezone('UTC')), 'prev_end_date_success': DateTime(2024, 9, 30, 14, 12, 40, 863729, tzinfo=Timezone('UTC')), 'run_id': 'manual__2024-09-30T14:19:58+00:00', 'task': <Task(PythonOperator): first_task>, 'task_instance': <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:19:58+00:00 [running]>, 'task_instance_key_str': 'MI_PRIMER_DAG__first_task__20240930', 'test_mode': False, 'ti': <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:19:58+00:00 [running]>, 'tomorrow_ds': <Proxy at 0x7f5afca0b140 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'tomorrow_ds', '2024-10-01')>, 'tomorrow_ds_nodash': <Proxy at 0x7f5afca09ac0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'tomorrow_ds_nodash', '20241001')>, 'triggering_dataset_events': <Proxy at 0x7f5afca33ac0 with factory <function _get_template_context.<locals>.get_triggering_events at 0x7f5afca253a0>>, 'ts': '2024-09-30T14:19:58+00:00', 'ts_nodash': '20240930T141958', 'ts_nodash_with_tz': '20240930T141958+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': <Proxy at 0x7f5afcaa8040 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'yesterday_ds', '2024-09-29')>, 'yesterday_ds_nodash': <Proxy at 0x7f5afcaa8080 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5afca27ce0>, 'yesterday_ds_nodash', '20240929')>, 'templates_dict': None}
[2024-09-30T14:20:03.227+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 32, in execute_task
    raise AirFlowSkipException('La tarea fue omitida')
          ^^^^^^^^^^^^^^^^^^^^
NameError: name 'AirFlowSkipException' is not defined. Did you mean: 'AirflowSkipException'?
[2024-09-30T14:20:03.238+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-30T14:20:03.238+0000] {logging_mixin.py:190} INFO - Task start:2024-09-30 14:20:03.112223+00:00 end:2024-09-30 14:20:03.237948+00:00 duration:0.125725
[2024-09-30T14:20:03.239+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): first_task> dag:<DAG: MI_PRIMER_DAG> dagrun:<DagRun MI_PRIMER_DAG @ 2024-09-30 14:19:58+00:00: manual__2024-09-30T14:19:58+00:00, state:running, queued_at: 2024-09-30 14:20:00.640706+00:00. externally triggered: True>
[2024-09-30T14:20:03.239+0000] {logging_mixin.py:190} INFO - Failure caused by name 'AirFlowSkipException' is not defined
[2024-09-30T14:20:03.239+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=MI_PRIMER_DAG, task_id=first_task, run_id=manual__2024-09-30T14:19:58+00:00, execution_date=20240930T141958, start_date=20240930T142003, end_date=20240930T142003
[2024-09-30T14:20:03.251+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-30T14:20:03.252+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 104 for task first_task (name 'AirFlowSkipException' is not defined; 69)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 32, in execute_task
    raise AirFlowSkipException('La tarea fue omitida')
          ^^^^^^^^^^^^^^^^^^^^
NameError: name 'AirFlowSkipException' is not defined. Did you mean: 'AirflowSkipException'?
[2024-09-30T14:20:03.267+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-30T14:20:03.283+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T14:20:03.286+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
