[2024-09-30T14:35:18.719+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-30T14:35:18.730+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:30:12+00:00 [queued]>
[2024-09-30T14:35:18.736+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:30:12+00:00 [queued]>
[2024-09-30T14:35:18.737+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 5
[2024-09-30T14:35:18.746+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): first_task> on 2024-09-30 14:30:12+00:00
[2024-09-30T14:35:18.751+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T14:35:18.753+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2024-09-30T14:35:18.752+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'MI_PRIMER_DAG', 'first_task', 'manual__2024-09-30T14:30:12+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/MI_PRIMER_DAG.py', '--cfg-path', '/tmp/tmpq0cmwf1_']
[2024-09-30T14:35:18.753+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask first_task
[2024-09-30T14:35:18.783+0000] {task_command.py:467} INFO - Running <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:30:12+00:00 [running]> on host b81766f0ac39
[2024-09-30T14:35:18.841+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='MI_PRIMER_DAG' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T14:30:12+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-30T14:30:12+00:00'
[2024-09-30T14:35:18.842+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-30T14:35:18.843+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-30T14:35:18.843+0000] {logging_mixin.py:190} INFO - Current task name:first_task state:running start_date:2024-09-30 14:35:18.731444+00:00
[2024-09-30T14:35:18.844+0000] {logging_mixin.py:190} INFO - Dag name:MI_PRIMER_DAG and current dag run status:running
[2024-09-30T14:35:18.844+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-30T14:35:18.845+0000] {logging_mixin.py:190} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7f7c36528a10>, 'dag': <DAG: MI_PRIMER_DAG>, 'dag_run': <DagRun MI_PRIMER_DAG @ 2024-09-30 14:30:12+00:00: manual__2024-09-30T14:30:12+00:00, state:running, queued_at: 2024-09-30 14:30:15.417812+00:00. externally triggered: True>, 'data_interval_end': DateTime(2024, 9, 30, 9, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2024, 9, 29, 9, 0, 0, tzinfo=Timezone('UTC')), 'outlet_events': <***.utils.context.OutletEventAccessors object at 0x7f7c0c458560>, 'ds': '2024-09-30', 'ds_nodash': '20240930', 'execution_date': <Proxy at 0x7f7c0c731f40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'execution_date', DateTime(2024, 9, 30, 14, 30, 12, tzinfo=Timezone('UTC')))>, 'expanded_ti_count': None, 'inlets': [], 'inlet_events': InletEventsAccessors(_inlets=[], _datasets={}, _dataset_aliases={}, _session=<sqlalchemy.orm.session.Session object at 0x7f7c3656d2b0>), 'logical_date': DateTime(2024, 9, 30, 14, 30, 12, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.12/site-packages/***/macros/__init__.py'>, 'map_index_template': None, 'next_ds': <Proxy at 0x7f7c0c576b40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'next_ds', '2024-09-30')>, 'next_ds_nodash': <Proxy at 0x7f7c0c2cc6c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'next_ds_nodash', '20240930')>, 'next_execution_date': <Proxy at 0x7f7c0c43eec0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'next_execution_date', DateTime(2024, 9, 30, 14, 30, 12, tzinfo=Timezone('UTC')))>, 'outlets': [], 'params': {'Manual': True}, 'prev_data_interval_start_success': DateTime(2024, 9, 29, 9, 0, 0, tzinfo=Timezone('UTC')), 'prev_data_interval_end_success': DateTime(2024, 9, 30, 9, 0, 0, tzinfo=Timezone('UTC')), 'prev_ds': <Proxy at 0x7f7c0c4553c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'prev_ds', '2024-09-30')>, 'prev_ds_nodash': <Proxy at 0x7f7c0c2be280 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'prev_ds_nodash', '20240930')>, 'prev_execution_date': <Proxy at 0x7f7c0c77ca80 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'prev_execution_date', DateTime(2024, 9, 30, 14, 30, 12, tzinfo=Timezone('UTC')))>, 'prev_execution_date_success': <Proxy at 0x7f7c0c4bfa80 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'prev_execution_date_success', DateTime(2024, 9, 30, 14, 19, 58, tzinfo=Timezone('UTC')))>, 'prev_start_date_success': DateTime(2024, 9, 30, 14, 20, 1, 19486, tzinfo=Timezone('UTC')), 'prev_end_date_success': DateTime(2024, 9, 30, 14, 25, 5, 245745, tzinfo=Timezone('UTC')), 'run_id': 'manual__2024-09-30T14:30:12+00:00', 'task': <Task(PythonOperator): first_task>, 'task_instance': <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:30:12+00:00 [running]>, 'task_instance_key_str': 'MI_PRIMER_DAG__first_task__20240930', 'test_mode': False, 'ti': <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-30T14:30:12+00:00 [running]>, 'tomorrow_ds': <Proxy at 0x7f7c0c463f40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'tomorrow_ds', '2024-10-01')>, 'tomorrow_ds_nodash': <Proxy at 0x7f7c0c463ec0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'tomorrow_ds_nodash', '20241001')>, 'triggering_dataset_events': <Proxy at 0x7f7c0c46ff80 with factory <function _get_template_context.<locals>.get_triggering_events at 0x7f7c0c451800>>, 'ts': '2024-09-30T14:30:12+00:00', 'ts_nodash': '20240930T143012', 'ts_nodash_with_tz': '20240930T143012+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': <Proxy at 0x7f7c0c462100 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'yesterday_ds', '2024-09-29')>, 'yesterday_ds_nodash': <Proxy at 0x7f7c0c482d80 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f7c0c453ec0>, 'yesterday_ds_nodash', '20240929')>, 'templates_dict': None}
[2024-09-30T14:35:18.852+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 32, in execute_task
    raise AirflowException('La tarea ha fallado')
airflow.exceptions.AirflowException: La tarea ha fallado
[2024-09-30T14:35:18.859+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-30T14:35:18.860+0000] {logging_mixin.py:190} INFO - Task start:2024-09-30 14:35:18.731444+00:00 end:2024-09-30 14:35:18.859524+00:00 duration:0.12808
[2024-09-30T14:35:18.860+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): first_task> dag:<DAG: MI_PRIMER_DAG> dagrun:<DagRun MI_PRIMER_DAG @ 2024-09-30 14:30:12+00:00: manual__2024-09-30T14:30:12+00:00, state:running, queued_at: 2024-09-30 14:30:15.417812+00:00. externally triggered: True>
[2024-09-30T14:35:18.860+0000] {logging_mixin.py:190} INFO - Failure caused by La tarea ha fallado
[2024-09-30T14:35:18.860+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=MI_PRIMER_DAG, task_id=first_task, run_id=manual__2024-09-30T14:30:12+00:00, execution_date=20240930T143012, start_date=20240930T143518, end_date=20240930T143518
[2024-09-30T14:35:18.870+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-30T14:35:18.870+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 109 for task first_task (La tarea ha fallado; 143)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 32, in execute_task
    raise AirflowException('La tarea ha fallado')
airflow.exceptions.AirflowException: La tarea ha fallado
[2024-09-30T14:35:18.887+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-30T14:35:18.903+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T14:35:18.905+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
