[2024-12-16T14:35:10.244+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-16T14:35:10.255+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.first_task manual__2024-12-16T14:34:45+00:00 [queued]>
[2024-12-16T14:35:10.260+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.first_task manual__2024-12-16T14:34:45+00:00 [queued]>
[2024-12-16T14:35:10.261+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-16T14:35:10.269+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): first_task> on 2024-12-16 14:34:45+00:00
[2024-12-16T14:35:10.275+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-16T14:35:10.277+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2024-12-16T14:35:10.277+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'MI_PRIMER_DAG', 'first_task', 'manual__2024-12-16T14:34:45+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/MI_PRIMER_DAG.py', '--cfg-path', '/tmp/tmpqpp26u40']
[2024-12-16T14:35:10.278+0000] {standard_task_runner.py:105} INFO - Job 131: Subtask first_task
[2024-12-16T14:35:10.313+0000] {task_command.py:467} INFO - Running <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-12-16T14:34:45+00:00 [running]> on host 590f5de10d76
[2024-12-16T14:35:10.373+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='MI_PRIMER_DAG' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T14:34:45+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T14:34:45+00:00'
[2024-12-16T14:35:10.374+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-16T14:35:10.375+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-16T14:35:10.375+0000] {logging_mixin.py:190} INFO - Current task name:first_task state:running start_date:2024-12-16 14:35:10.255700+00:00
[2024-12-16T14:35:10.375+0000] {logging_mixin.py:190} INFO - Dag name:MI_PRIMER_DAG and current dag run status:running
[2024-12-16T14:35:10.376+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-16T14:35:10.376+0000] {logging_mixin.py:190} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7f39b30eccb0>, 'dag': <DAG: MI_PRIMER_DAG>, 'dag_run': <DagRun MI_PRIMER_DAG @ 2024-12-16 14:34:45+00:00: manual__2024-12-16T14:34:45+00:00, state:running, queued_at: 2024-12-16 14:35:08.603744+00:00. externally triggered: True>, 'data_interval_end': DateTime(2024, 12, 16, 9, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2024, 12, 15, 9, 0, 0, tzinfo=Timezone('UTC')), 'outlet_events': <***.utils.context.OutletEventAccessors object at 0x7f3983d997f0>, 'ds': '2024-12-16', 'ds_nodash': '20241216', 'execution_date': <Proxy at 0x7f3983ee8b40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'execution_date', DateTime(2024, 12, 16, 14, 34, 45, tzinfo=Timezone('UTC')))>, 'expanded_ti_count': None, 'inlets': [], 'inlet_events': InletEventsAccessors(_inlets=[], _datasets={}, _dataset_aliases={}, _session=<sqlalchemy.orm.session.Session object at 0x7f39b20198e0>), 'logical_date': DateTime(2024, 12, 16, 14, 34, 45, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.12/site-packages/***/macros/__init__.py'>, 'map_index_template': None, 'next_ds': <Proxy at 0x7f3983de1fc0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'next_ds', '2024-12-16')>, 'next_ds_nodash': <Proxy at 0x7f3983dd61c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'next_ds_nodash', '20241216')>, 'next_execution_date': <Proxy at 0x7f3983daff40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'next_execution_date', DateTime(2024, 12, 16, 14, 34, 45, tzinfo=Timezone('UTC')))>, 'outlets': [], 'params': {'Manual': True}, 'prev_data_interval_start_success': DateTime(2024, 12, 15, 9, 0, 0, tzinfo=Timezone('UTC')), 'prev_data_interval_end_success': DateTime(2024, 12, 16, 9, 0, 0, tzinfo=Timezone('UTC')), 'prev_ds': <Proxy at 0x7f3983dad480 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'prev_ds', '2024-12-16')>, 'prev_ds_nodash': <Proxy at 0x7f3983c16400 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'prev_ds_nodash', '20241216')>, 'prev_execution_date': <Proxy at 0x7f3983d1aa40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'prev_execution_date', DateTime(2024, 12, 16, 14, 34, 45, tzinfo=Timezone('UTC')))>, 'prev_execution_date_success': <Proxy at 0x7f3983d1b440 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'prev_execution_date_success', DateTime(2024, 12, 15, 9, 0, 0, tzinfo=Timezone('UTC')))>, 'prev_start_date_success': DateTime(2024, 12, 16, 14, 6, 56, 565675, tzinfo=Timezone('UTC')), 'prev_end_date_success': DateTime(2024, 12, 16, 14, 7, 0, 946625, tzinfo=Timezone('UTC')), 'run_id': 'manual__2024-12-16T14:34:45+00:00', 'task': <Task(PythonOperator): first_task>, 'task_instance': <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-12-16T14:34:45+00:00 [running]>, 'task_instance_key_str': 'MI_PRIMER_DAG__first_task__20241216', 'test_mode': False, 'ti': <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-12-16T14:34:45+00:00 [running]>, 'tomorrow_ds': <Proxy at 0x7f3983d1a0c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'tomorrow_ds', '2024-12-17')>, 'tomorrow_ds_nodash': <Proxy at 0x7f3983f9ca00 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'tomorrow_ds_nodash', '20241217')>, 'triggering_dataset_events': <Proxy at 0x7f3983dc0c40 with factory <function _get_template_context.<locals>.get_triggering_events at 0x7f3983da5760>>, 'ts': '2024-12-16T14:34:45+00:00', 'ts_nodash': '20241216T143445', 'ts_nodash_with_tz': '20241216T143445+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': <Proxy at 0x7f3983c24540 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'yesterday_ds', '2024-12-15')>, 'yesterday_ds_nodash': <Proxy at 0x7f3983c24a40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f3983da7ce0>, 'yesterday_ds_nodash', '20241215')>, 'templates_dict': None}
[2024-12-16T14:35:10.382+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 34, in execute_task
    raise AirflowException('La tarea a fallado.')
airflow.exceptions.AirflowException: La tarea a fallado.
[2024-12-16T14:35:10.389+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-16T14:35:10.389+0000] {logging_mixin.py:190} INFO - Task start:2024-12-16 14:35:10.255700+00:00 end:2024-12-16 14:35:10.388918+00:00 duration:0.133218
[2024-12-16T14:35:10.390+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): first_task> dag:<DAG: MI_PRIMER_DAG> dagrun:<DagRun MI_PRIMER_DAG @ 2024-12-16 14:34:45+00:00: manual__2024-12-16T14:34:45+00:00, state:running, queued_at: 2024-12-16 14:35:08.603744+00:00. externally triggered: True>
[2024-12-16T14:35:10.390+0000] {logging_mixin.py:190} INFO - Failure caused by La tarea a fallado.
[2024-12-16T14:35:10.390+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=MI_PRIMER_DAG, task_id=first_task, run_id=manual__2024-12-16T14:34:45+00:00, execution_date=20241216T143445, start_date=20241216T143510, end_date=20241216T143510
[2024-12-16T14:35:10.402+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-16T14:35:10.403+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 131 for task first_task (La tarea a fallado.; 85)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 34, in execute_task
    raise AirflowException('La tarea a fallado.')
airflow.exceptions.AirflowException: La tarea a fallado.
[2024-12-16T14:35:10.451+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-16T14:35:10.465+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-16T14:35:10.467+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
